-- MySQL schema for PetziGo
CREATE DATABASE IF NOT EXISTS petzigo DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE petzigo;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(160) NOT NULL,
  email VARCHAR(160) NOT NULL UNIQUE,
  document_type VARCHAR(2),
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('USER','PROVIDER','ADMIN') NOT NULL DEFAULT 'USER',
  user_type ENUM('BUYER','PROVIDER') NOT NULL,
  phone VARCHAR(40),
  address VARCHAR(255),
  legal_representative VARCHAR(160),
  company_name VARCHAR(160),
  nit VARCHAR(20),
  tax_id VARCHAR(80),
  status ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  documents_status ENUM('PENDING','REQUESTED','SUBMITTED','APPROVED','REJECTED') NOT NULL DEFAULT 'PENDING',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  provider_id INT NOT NULL,
  name VARCHAR(140) NOT NULL,
  description TEXT,
  price DECIMAL(10,2) NOT NULL DEFAULT 0,
  stock INT NOT NULL DEFAULT 0,
  visible TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (provider_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS services (
  id INT AUTO_INCREMENT PRIMARY KEY,
  provider_id INT NOT NULL,
  title VARCHAR(140) NOT NULL,
  description TEXT NOT NULL,
  price DECIMAL(10,2) NOT NULL DEFAULT 0,
  available TINYINT(1) DEFAULT 1,
  active TINYINT(1) DEFAULT 1,
  visible TINYINT(1) DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (provider_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS orders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  provider_id INT NOT NULL,
  item_type ENUM('SERVICE','PRODUCT') NOT NULL,
  service_id INT NULL,
  product_id INT NULL,
  quantity INT NOT NULL DEFAULT 1,
  status ENUM('PENDING','IN_PROCESS','SHIPPED','DELIVERED','CANCELLED') DEFAULT 'PENDING',
  notes TEXT,
  requested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  delivery_date DATE NULL,
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (provider_id) REFERENCES users(id),
  FOREIGN KEY (service_id) REFERENCES services(id),
  FOREIGN KEY (product_id) REFERENCES products(id)
);
CREATE INDEX idx_orders_status ON orders(status, item_type);
CREATE INDEX idx_orders_requested_at ON orders(requested_at);

CREATE TABLE IF NOT EXISTS order_status_history (
  id INT AUTO_INCREMENT PRIMARY KEY,
  order_id INT NOT NULL,
  old_status ENUM('PENDING','IN_PROCESS','SHIPPED','DELIVERED','CANCELLED') NOT NULL,
  new_status ENUM('PENDING','IN_PROCESS','SHIPPED','DELIVERED','CANCELLED') NOT NULL,
  changed_by INT NOT NULL,
  changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (order_id) REFERENCES orders(id),
  FOREIGN KEY (changed_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS user_documents (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  document_type ENUM('IDENTIFICATION','LEGAL','BANK','OTHER') NOT NULL DEFAULT 'OTHER',
  status ENUM('REQUESTED','SUBMITTED','APPROVED','REJECTED') NOT NULL DEFAULT 'REQUESTED',
  file_url VARCHAR(255),
  observations TEXT,
  requested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  submitted_at TIMESTAMP NULL,
  reviewed_at TIMESTAMP NULL,
  FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS reviews (
  id INT AUTO_INCREMENT PRIMARY KEY,
  order_id INT NOT NULL,
  rating TINYINT NOT NULL,
  comment TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (order_id) REFERENCES orders(id)
);
